import { MenuItem } from "./menu.model";

export const SUBMENU: any = [
  //   {
  //     id: 1,
  //     label: "MENU",
  //     isTitle: true,
  //   },
  //   {
  //     id: 2,
  //     label: "DASHBOARD",
  //     icon: "ri-dashboard-2-line",
  //     link: "/",
  //   },
  {
    id: 3,
    label: "LEADS",
    icon: "ri-rocket-line",
    subItems: [
      {
        id: 301,
        label: "Leads",
        icon: " ri-user-settings-line",

        subItems: [
          {
            id: 30109,
            label: "All Leads",
            link: "/leads",
            parentId: 301,
          },
          {
            id: 30110,
            label: "Accounts",
            link: "/pages/coming-soon",
            parentId: 301,
          },
          {
            id: 30111,
            label: "Contacts",
            link: "/leads/accounts",
            parentId: 301,
          },
          {
            id: 30112,
            label: "Opportunities",
            link: "/leads/accounts",
            parentId: 301,
          },
          {
            id: 30113,
            label: "Quotations",
            link: "/leads/accounts",
            parentId: 301,
          },
        ],
      },
      {
        id: 302,
        label: "Reservations ",
        icon: " ri-pages-line",
        link: "/reservations",
        parentId: 302,
      },
      {
        id: 303,
        label: "Contacts ",
        icon: "ri-contacts-line",
        subItems: [
          {
            id: 30310,
            label: "Contracts",
            link: "/leads/accounts",
            parentId: 303,
          },
          {
            id: 30311,
            label: "Addendums",
            link: "/leads/accounts",
            parentId: 303,
          },
          {
            id: 30312,
            label: "Terminations",
            link: "/leads/accounts",
            parentId: 303,
          },
          {
            id: 30313,
            label: "Temporary lease extensions",
            link: "/leads/accounts",
            parentId: 303,
          },
        ],
      },
      {
        id: 304,
        label: "Configurations",
        icon: "ri-file-settings-line",
        subItems: [
          {
            id: 30410,
            label: "Lead sources",
            link: "/leads/accounts",
            parentId: 304,
          },
          {
            id: 30411,
            label: "Property locations",
            link: "/leads/accounts",
            parentId: 304,
          },
          {
            id: 30412,
            label: "Neighborhood ",
            link: "/leads/accounts",
            parentId: 304,
          },
          {
            id: 30413,
            label: "Lead stages ",
            link: "/leads/accounts",
            parentId: 304,
          },
          {
            id: 30414,
            label: "Lost reasons ",
            link: "/leads/accounts",
            parentId: 304,
          },
          {
            id: 30415,
            label: "Nationalities ",
            link: "/leads/accounts",
            parentId: 304,
          },
        ],
      },
      {
        id: 305,
        label: "External Agencies",
        icon: "ri-team-line",
        subItems: [
          {
            id: 30510,
            label: "Agencies ",
            link: "/leads/accounts",
            parentId: 305,
          },
          {
            id: 30511,
            label: "Bookings and Commissions",
            link: "/leads/accounts",
            parentId: 305,
          },
        ],
      },
      {
        id: 306,
        label: "Activities",
        icon: " ri-survey-line",
        subItems: [
          {
            id: 30610,
            label: "Tasks ",
            link: "/leads/accounts",
            parentId: 306,
          },
          {
            id: 30611,
            label: "Appointments ",
            link: "/leads/accounts",
            parentId: 306,
          },
        ],
      },
      {
        id: 307,
        label: "Accounts",
        icon: " ri-account-box-line",
        link: "/accounts",
        parentId: 3,
      },

      {
        id: 308,
        label: "Opportunities ",
        icon: " ri-body-scan-fill",
        link: "/opportunities",
        parentId: 3,
      },
      {
        id: 309,
        label: "Quotations ",
        icon: " ri-briefcase-4-line",
        link: "/quotations",
        parentId: 3,
      },

      {
        id: 310,
        label: "Contracts ",
        icon: "ri-newspaper-line",
        link: "/contracts ",
        parentId: 3,
      },
      {
        id: 311,
        label: "Addendums ",
        icon: "ri-file-paper-line",
        link: "/addendums ",
        parentId: 3,
      },
      {
        id: 312,
        label: "Terminations ",
        icon: "ri-file-forbid-line",
        link: "/terminations ",
        parentId: 3,
      },
      {
        id: 313,
        label: "Temporary lease extensions",
        icon: "ri-file-list-line",
        link: "/lease-extensions",
        parentId: 3,
      },
    ],
  },
  {
    id: 4,
    label: "PROPERTIES",
    icon: "ri-rocket-line",
    subItems: [
      {
        id: 411,
        label: "Properties",
        icon: "ri-building-line",
        subItems: [
          {
            id: 41110,
            label: "Company codes",
            link: "/configurations /sweetalerts",
            parentId: 411,
          },
          {
            id: 41111,
            label: "Buildings",
            link: "/configurations /sweetalerts",
            parentId: 311,
          },
          {
            id: 41112,
            label: "Business Entities",
            link: "/configurations /sweetalerts",
            parentId: 411,
          },
          {
            id: 41113,
            label: "Building Types",
            link: "/configurations /sweetalerts",
            parentId: 411,
          },
          {
            id: 41114,
            label: "Unit Types",
            link: "/configurations /sweetalerts",
            parentId: 411,
          },
          {
            id: 41115,
            label: "Units ",
            link: "/configurations /sweetalerts",
            parentId: 411,
          },
          {
            id: 41116,
            label: "Parking ",
            link: "/configurations /sweetalerts",
            parentId: 411,
          },
          {
            id: 41117,
            label: "Utilities ",
            link: "/configurations /sweetalerts",
            parentId: 411,
          },
        ],
      },
      {
        id: 412,
        label: "Pricing",
        icon: "ri-price-tag-3-line",
        subItems: [
          {
            id: 41210,
            label: "Unit pricing ",
            link: "/externalagencies/sweetalerts",
            parentId: 412,
          },
          {
            id: 41211,
            label: "Utility pricing ",
            link: "/externalagencies/sweetalerts",
            parentId: 412,
          },
        ],
      },

      {
        id: 413,
        label: "Unit Occupancies",
        icon: "ri-community-line",
        link: "/unit",
        parentId: 4,
      },
      {
        id: 414,
        label: "Parking Allocation",
        icon: "ri-parking-box-line",
        link: "/accounts",
        parentId: 4,
      },
      {
        id: 415,
        label: "Vendors ",
        icon: "ri-group-line",
        link: "/contacts",
        parentId: 4,
      },
      {
        id: 416,
        label: "Services ",
        icon: "ri-service-line",
        link: "/opportunities",
        parentId: 4,
      },
    ],
  },
  {
    id: 5,
    label: "TENANTS ",
    icon: "ri-rocket-line",
    subItems: [
      {
        id: 501,
        label: "Tenants and Companions",
        icon: "ri-group-2-line",
        link: "/tenents",
        parentId: 5,
      },
      {
        id: 502,
        label: "Move in",
        icon: "ri-arrow-left-circle-line",
        link: "/accounts",
        parentId: 5,
      },
      {
        id: 503,
        label: "Move out  ",
        icon: "ri-arrow-right-circle-line",
        link: "/contacts",
        parentId: 5,
      },
      {
        id: 504,
        label: "Service requests  ",
        icon: "ri-user-settings-line",
        link: "/opportunities",
        parentId: 5,
      },
      {
        id: 505,
        label: "Support tickets/maintenance requests",
        icon: "ri-coupon-line",
        link: "/quotations",
        parentId: 5,
      },
      {
        id: 506,
        label: "Announcements ",
        icon: "ri-notification-3-line",
        link: "/reservations",
        parentId: 5,
      },
      {
        id: 507,
        label: "Warnings ",
        icon: "ri-error-warning-line",
        link: "/contracts ",
        parentId: 5,
      },
      {
        id: 508,
        label: "Greetings ",
        icon: "ri-hand-heart-line",
        link: "/addendums ",
        parentId: 5,
      },
      {
        id: 509,
        label: "Blacklisted  ",
        icon: "ri-spam-line",
        link: "/terminations ",
        parentId: 5,
      },
      {
        id: 510,
        label: "Visitors / Deliveries ",
        icons: "ri-parent-line",
        link: "/lease-extensions",
        parentId: 5,
      },
      {
        id: 511,
        label: "Compensations  ",
        icon: "ri-money-dollar-circle-line",
        link: "/lease-extensions",
        parentId: 5,
      },
      {
        id: 512,
        label: "Non renewals ",
        icon: " ri-arrow-up-down-line",
        link: "/lease-extensions",
        parentId: 5,
      },
    ],
  },
  {
    id: 6,
    label: "SETTINGS",
    icon: "ri-rocket-line",
    subItems: [
      {
        id: 610,
        label: "Workflows",
        icon: "ri-list-settings-line",
        link: "/reservations",
        parentId: 6,
      },
      {
        id: 611,
        label: "SLA",
        icon: "ri-file-list-line",
        link: "/reservations",
        parentId: 6,
      },
      {
        id: 612,
        label: "Email templates",
        icon: "ri-mail-line",
        link: "/reservations",
        parentId: 6,
      },
      {
        id: 613,
        label: "CMS",
        icon: "ri-contacts-book-line",
        subItems: [
          {
            id: 61310,
            label: "FAQ",
            link: "/externalagencies/sweetalerts",
            parentId: 613,
          },
          {
            id: 61311,
            label: "Terms and conditions ",
            link: "/externalagencies/sweetalerts",
            parentId: 613,
          },
        ],
      },
      {
        id: 614,
        label: "Third party configurations",
        icon: "ri-stack-line",
        subItems: [
          {
            id: 61410,
            label: "Whatsapp ",
            link: "/externalagencies/sweetalerts",
            parentId: 614,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    label: "REPORTS",
    icon: "ri-rocket-line",
    subItems: [
      {
        id: 710,
        label: "Reports",
        icon: "ri-file-text-line",
        link: "/reservations",
        parentId: 7,
      },
      {
        id: 711,
        label: "Analytics",
        icon: " ri-file-search-line",
        link: "/reservations",
        parentId: 7,
      },
    ],
  },
  {
    id: 8,
    label: "APPROVALS",
    icon: "ri-rocket-line",
    link: "/approvals",
  },
  {
    id: 9,
    label: "USERS",
    icon: "ri-rocket-line",
    link: "/users",
  },
];
